---
layout: :theme/post
title: "OpenRewrite: Refactoring as code"
description: Introduction to OpenRewrite
image: https://images.unsplash.com/photo-1589152144820-692b189e0b34?q=80&w=3474&auto=format&fit=crop&ixlib=rb-4.0.3
tags: java, tools
author: jtama
draft: true
---

image::{site.url('/static/assets/images/openrewrite/logo.svg')}[Logo d'openrewrite]

So you want to refactor your code ? You have a several options that you usually use:

* To begin with, the *_in_*famous *Search and Replace*, better known as `Ctrl+F/Ctrl+R`
* The slightly more advanced _Regular Expressions_ technic
* But most probably, you will use your IDE's _Right Click_ menu

If you're refactoring takes more than one step and/or touches many files, you are most likely to fall back to a migration guide as sad as a rainy sunday.

Let's say you want to migrate from JUnit 4 to Junit 5, or from Spring Boot 2.3 to 2.4, or from Hibernate 4 to 5, or from Java 8 to 11, or from Guava to Java 8.
You will have to:

* Bump pom or maven dependencies
* Change imports
* Change annotations
* Change method signatures
* Maybe change method invocations
* ...

This is time-consuming, cumbersome and error-prone.

But there is a newcomer in the refactoring world: *OpenRewrite*.

== The big picture

OpenRewrite is a refactoring tool that was created by https://www.moderne.ai[Moderne].

It's an open source project licenced under the Apache 2.0 licence, and it's now part of the https://www.commonhaus.org/[Commonhaus Fondation].

It started with a strong focus on Java(and it's configuration files: properties and yaml), but it's now expanding to other languages, and file formats:

* Programming languages:
** Java
** Kotlin
** Groovy
* Data formats
** XML
** Properties
** YAML
** JSON
** Protobuf
* Build tools
** Maven
** Gradle

I will only focus on the Java ecosystem in this article.

== Concepts

The main OpenRewrite concepts you have to have in mind are the following.

The source code you want to lookup at and transform is made accessible to you through what they call an *_LST_*. A Lossless Syntax Tree is a representation of the source code that is as close as possible to the original source code, but with a few tweaks to make it easier to manipulate

The atomic piece to perform refactoring is called a _recipe_. it can have prechecks and one or more related transformations.

But it can also have a list of recipes which will apply sequentially, and thus the way to implement complex refactoring, is to compose _recipes_, and in the end is also called a recipe.

¯\\_(ツ)_/¯ Don't blame the messenger.


== What does it offer ?

OpenRewrite isn't just one thing actually, it's a set of tools that work together.

. The core module, of course, that contains all the generic language representation and common refactoring logic.
. One module for each language, with dedicated apis and sdk for a specific target (Java, XML, Yaml, etc)
. Many modules containing recipes for a specific subset of interest, such as testing frameworks recipes, spring recipes, quarkus recipes, static analysis issue identification and fixing, etc.
