name: Deploy PR Preview

on:
  workflow_run:
    workflows: [ "Build PR Preview" ]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write # Required to update PR status comment
    steps:
      - name: Download blog artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: blog

      - name: Publishing blog to Surge.sh
        id: deploy-blog
        run: npx surge ./ --domain https://jtama-${{ github.event.number }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Update PR status comment on success
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.number }}
          body: |
            🚀 PR Preview for **blog** ${{ github.sha }} has been successfully built!
            * https://onepoint-tech-${{ github.event.number }}-preview.surge.sh
          body-marker: <!-- Preview status comment marker -->
      - name: Update PR status comment on failure
        uses: quarkusio/action-helpers@main
        if: ${{ failure() }}
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.number }}
          body: |
            😭 Deploy PR Preview failed.
          body-marker: <!-- Preview status comment marker -->